import type { Metadata } from "next";
import { Inter, Holtwood_One_SC } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const holtwood = Holtwood_One_SC({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-holtwood",
});

export const metadata: Metadata = {
  title: "Giphy App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${holtwood.variable}`}>
        {children}
      </body>
    </html>
  );
}
